language: d

#compiler:
#  - dmd

install:
  # dmd
  - DMD_VERSION=2.061
  - wget http://downloads.dlang.org.s3-website-us-east-1.amazonaws.com/releases/2013/dmd.${DMD_VERSION}.zip
  - unzip dmd.${DMD_VERSION}.zip

script:
  - DMD=./dmd2/linux/bin32/dmd MODEL=32 make -f posix.mak unittest

branches:
  only:
    - master

notifications:
  email: true
